version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
      API_DOMAIN: "localhost:3009"
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    # command: bundle exec rails server -p 5000 -b '0.0.0.0'
    environment:
      API_DOMAIN: "localhost:3009"
      BASE_URL: "http://localhost:3009"
    volumes:
      - .:/myapp
    ports:
      - "5000:5000"
    depends_on:
      - db
